### ISSUE TITLE
[Chore] Skeleton Loader Atom & Toast 설계, Tanstack Query & Mock과 연동

### ISSUE THREAD

**Issue by ABizCho** [SolSolHigh/SolSolHigh-FE#17]
## 📔 Description

- Skeleton Loader Atom 설계 개발
- Toast 적용
- Tanstack Query 기본 설정
- Tanstack Query로 Msw 페칭 후, 케이스에 따른 Skeleton Loader, Toast 연동 및 테스트

## 🐈 Todo

- [x] Skeleton Loader Atom 설계 개발
- [x] Toast 적용
- [x] Tanstack Query 기본 설정
- [x] Tanstack Query로 Msw 페칭 후, 케이스에 따른 Skeleton Loader, Toast 연동 및 테스트
