### ISSUE TITLE
[Feat] Button Atom 컴포넌트 리팩토링, 확장 개발

### ISSUE THREAD

**Issue by ABizCho** [SolSolHigh/SolSolHigh-FE#30]
## 📔 Description
사전에 개발한 버튼 컴포넌트 초안을, 이후 추가된 쏠쏠하이의 디자인 시스템에 맞게 확장, 리팩토링하는 것을 목표로 합니다.

## 🐈 Todo
- [x] 정의된 Color Palette에 맞게 colorVariants 확장
- [x] disabled 색상 처리
- [x] 버튼 전용 colorVariants 자동 생성하는 유틸함수 개발 (DEPRECATED)

### 개발 중 이슈
버튼의 colorVariants에 따라 스타일 클래스명을 자동으로 조합해주는 함수를 개발했지만 제대로 적용되지 않는 문제가 있었습니다. 이는 Tailwind의 `JIT(Just In Time)` 모드 작동방식에 의한 문제로, 동적 클래스네임이 생성되기 전 이미 테일윈드의 렌더링이 완료되기 때문에 발생하는 문제라고 하네욥 @yh-project @altys31
