### ISSUE TITLE
[Feat] 퀴즈 메인페이지 UI 디자인

### ISSUE THREAD

**Issue by altys31** [SolSolHigh/SolSolHigh-FE#40]
## 📔 Description

퀴즈 메인페이지 UI 디자인 

## 🐈 Todo

- [x] 금일 퀴즈 풀이 여부 
- [x] 퀴즈 스트릭 확인 
- [x] 퀴즈 키워드 조회
- [x] 퀴즈 키워드 편집 (부모)
- [x] 퀴즈 내역 조회
- [x] 퀴즈 내역 상세 조회
