### ISSUE TITLE
[Feat] 사용자 정보 조회 페이지 & 네비게이션 바

### ISSUE THREAD

**Issue by yh-project** [SolSolHigh/SolSolHigh-FE#48]
## 📔 Description

사용자 정보 조회 페이지 구현

## 🐈 Todo

- [x] InfoList molecules component 구현
- [x] 사용자 정보 조회 페이지 구현
- [x] 부모의 자녀 관리 페이지 구현
