### ISSUE TITLE
[Chore] Msw, Axios, Recoil 기본 설정

### ISSUE THREAD

**Issue by ABizCho** [SolSolHigh/SolSolHigh-FE#5]
## 📔 Description

Msw, Axios, Recoil 기본 설정을 위한 이슈입니다.
## 🐈 Todo

- [x] Msw 기본 설정
- [x] Axios 기본 설정
- [x] Recoil 기본 설정
