### ISSUE TITLE
[Feat] 약속권 페이지 UI 디자인 & 모킹

### ISSUE THREAD

**Issue by altys31** [SolSolHigh/SolSolHigh-FE#54]
## 📔 Description

약속권 페이지 UI 디자인 & 모킹

## 🐈 Todo

- [x] 보유한 약속권 조회
- [x] 약속 요청하기 [자녀]
- [x] 약속 지키기 [부모]
- [x] 약속 조회
