### ISSUE TITLE
[Feat] 계좌 UI 디자인 및 모킹

### ISSUE THREAD

**Issue by altys31** [SolSolHigh/SolSolHigh-FE#59]
## 📔 Description

 계좌 UI 디자인 및 모킹

## 🐈 Todo

- [x] 통장관리 페이지
- [x] 계좌 개설 권유 페이지
- [x] 상품 목록 페이지
- [x] 상품 설명 페이지
- [x] 해지시 상품 권유 페이지
- [x] 계좌 카드 컴포넌트
- [x] 송금 모달
- [x] 예약 이체 모달
- [x] 자동 이체 모달
- [x] 예금 계좌 개설 모달
- [x] 적금 계좌 개설 모달
- [x] 계좌 거래 내역 모달
- [x] 관리 자녀 변경 컴포넌트
