### ISSUE TITLE
[Feat] 퀴즈, 약속권, 계좌 담당 도메인 api 연결

### ISSUE THREAD

**Issue by altys31** [SolSolHigh/SolSolHigh-FE#68]
## 📔 Description

퀴즈, 약속권, 계좌 담당 도메인 api 연결

## 🐈 Todo

- [ ] 퀴즈 api 연결
- [ ] 약속권 api 연결
- [ ] 계좌 api 연결
