### ISSUE TITLE
[FIX] 계란/마켓 로직 수정, 보완

### ISSUE THREAD

**Issue by ABizCho** [SolSolHigh/SolSolHigh-FE#69]
## 📔 Description
1. 계란 10개 다깨고 나면 터치안되게 예외처리 + ( 오늘의 계란을 다 깼어요 ), 보상 오는 중 예외처리

2. 특별한 계란 이름 정적인거 수정

3. 구매 시, 리스트에서 안사라짐

4. 내 계란 판매글에 구매하기 버튼 없애기

## 🐈 Todo

- [x] 0. 아이의 내 미션 도전자명 표시

- [x] 1. 계란 10개 다깨고 나면 터치안되게 예외처리 + ( 오늘의 계란을 다 깼어요 ), 보상 오는 중 예외처리

- [x] 2. 특별한 계란 이름 정적인거 수정

- [x] 3. 구매 시, 리스트에서 안사라짐

- [ ] 4. 내 계란 판매글에 구매하기 버튼 없애기 -> 다시 확인

- [x] 5. 부모 미션 수정하기 버튼 클릭 시 나올 수정 폼 만들기

- [ ] 6. 부모 아이들의 미션보기 페이지네이션, 데이터 안오면, 페이지네이션 페이지 크기 벗어나면 다음 버튼 비활성화, 다음 버튼 비활성화.

- [x] 7. 계란 검색 desc, asc 작동 안하는거 현진이한테 확인받기 (보류)

- [x] 8. 계란 가격 정수만 반환하도록 현진이한테 요청하기

- [x] 9. 거래된적없는 계란 차트 ui 따로 만들기

- [x] 10. 계란 삭제하기 400 에러: 잘못된 메서드 => delete로 수정

- [x] 11. 내가 판매중인 계란 확인해서 판매등록폼에서 제외, 

- [x] 12. 구매 시, 계란 포인트  업데이트

- [x] 13. 저축계좌 없는 경우, 빈계란 처리, 클릭 시 Alert 혹은 Toast로 부모님에게 저축계좌 만들어달라고 조르기

- [ ] 14. 계란 터질 시, 특별한 계란뿐 아니라 100원 저축했다고 알림
- [ ] 계란 10개 다 깬 경우, 그만터치해 처리
- [x] 부모의 미션 생성, 수정 제출 시 날짜 포매팅 수정
